version: '3.8'

services:
  api:
    build: .
    container_name: bet_api_service
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    # Se no futuro quiser adicionar o Postgres, basta colocar aqui embaixo