version: '3.8'

services:
  api:
    build: .
    container_name: bet_api_service
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  ui:
    build: .
    container_name: bet_ui_streamlit
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    command: streamlit run app/presentation/home.py --server.port=8501 --server.address=0.0.0.0